### ISSUE TITLE
Native extensions are building horribly.

### ISSUE THREAD

**Issue by Southern** [nodejitsu/module-foundry#14]
Since we now support 0.10.x, we should make module-foundry read the package.json of the user and build with the Node version that is specified in their package.json. Without this, we run into module version mismatch errors on native extensions that are built on module-foundry and then used on another version of Node.

For instance: `Error: Module version mismatch. Expected 11, got 1.`

This is forcing users with native extensions to continue to use 0.8.x rather than 0.10.x because native extensions aren't available with the current build process.

**Comment by Swaagie** [comment]
+1 per example: https://github.com/mapbox/node-sqlite3/blob/master/build.js#L75-L87

@indexzero is this fixed in the new rollout?

During devops I updated module-foundry to 0.10 for ghost users, most binaries allow use of 0.10. Combinations of versions can be anything though. https://github.com/nodejitsu/devops-shift-logs/blob/master/swaagie/2013-10-24/index.md

**Comment by indexzero** [comment]
This is fixed
